namespace DataStructureAndAlgorithms.LeetCode;

public static class ProgrammingSkills
{
    /// <summary>
    /// You are given two strings s and t.
    // String t is generated by random shuffling string s and then add one more letter at a random position.
    // Return the letter that was added to t.
    /// </summary>
    /// <param name="s"></param>
    /// <param name="t"></param>
    /// <returns></returns>
    public static char FindTheDifference(string s, string t)
    {
        int i = 0;

        while (i < s.Length)
        {
            if (s[i] != s[i])
                break;
            i++;
        }

        return t[i];
    }
}