using System.Collections.Generic;

namespace DataStructureAndAlgorithms.LeetCode;

public static class ProgrammingSkills
{
    /// <summary>
    /// You are given two strings s and t.
    // String t is generated by random shuffling string s and then add one more letter at a random position.
    // Return the letter that was added to t.
    /// </summary>
    /// <param name="s"></param>
    /// <param name="t"></param>
    /// <returns></returns>
    public static char FindTheDifference(string s, string t)
    {
        const int ASCII_SIZE = 256;
        int[] frequencies = new int[ASCII_SIZE];
        foreach (char @char in s)
        {
            frequencies[@char]++;
        }

        foreach(char @char in t)
        {
            if (frequencies[@char] == 0)
                return @char;
            frequencies[@char]--;
        }
        return default;
    }

    
    public static int FindIndexOfFirstOccurrence(string text, string target)
    {
        for (int i = 0; i <= text.Length - target.Length; i++)
        {
            if(text.Substring(i, target.Length) == target)
                return i;
        }

        return -1;
    }
}